# Generated by Django 6.0.1 on 2026-02-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_sender_receiver_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed Delivery'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
