# Generated by Django 6.0.1 on 2026-02-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_delivery_failure_reason_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
