# Generated by Django 6.0.1 on 2026-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='gcash_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='gcash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
