# Generated by Django 6.0.1 on 2026-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_deliveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='gcash_proof',
            field=models.ImageField(blank=True, null=True, upload_to='gcash_proofs/'),
        ),
    ]
