# Generated by Django 6.0.2 on 2026-04-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymongo_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymongo_source_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('GCASH', 'GCash'), ('COD', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='withdrawal_method',
            field=models.CharField(choices=[('BANK', 'Bank Transfer'), ('GCASH', 'GCash')], max_length=20),
        ),
    ]
