# Generated by Django 6.0.2 on 2026-04-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit/Debit Card'), ('COD', 'Cash on Delivery')], max_length=20),
        ),
    ]
