# Generated by Django 6.0.1 on 2026-02-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('RIDER', 'Rider'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10),
        ),
    ]
