# Generated by Django 6.0.1 on 2026-02-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_type'),
        ('user', '0006_user_is_approved'),
    ]

    operations = [
    ]
