# Generated by Django 6.0.1 on 2026-02-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_0006_alter_user_user_type_0006_user_is_approved'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
