# Generated by Django 6.0.1 on 2026-03-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_online'),
        ('user', '0009_user_push_token'),
    ]

    operations = [
    ]
