# Generated by Django 6.0.1 on 2026-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_0002_user_is_online_0009_user_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('RIDER', 'Rider'), ('ADMIN', 'Admin'), ('CASHIER', 'Cashier')], default='CUSTOMER', max_length=10),
        ),
    ]
