# Generated by Django 6.0.1 on 2026-04-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_pending_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
