# Generated by Django 6.0.1 on 2026-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcash_qr',
            field=models.ImageField(blank=True, null=True, upload_to='gcash_qr/'),
        ),
    ]
