# Generated by Django 6.0.1 on 2026-04-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_add_gcash_qr_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='extra_data',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='rider_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_left',
            field=models.ImageField(blank=True, null=True, upload_to='rider_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_right',
            field=models.ImageField(blank=True, null=True, upload_to='rider_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='user.branch'),
        ),
    ]
